#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/init.d/qemu-system-x86 2.1+dfsg-4ubuntu4~ -- "$@"
# End automatically added section
dpkg-maintscript-helper rm_conffile /etc/init.d/qemu-system-x86 1:2.2+dfsg-3~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/qemu/target-x86_64.conf 1:2.4+dfsg-1~ -- "$@"
[ -d /etc/qemu ] && rmdir /etc/qemu 2>/dev/null || :
